### ISSUE TITLE
error @ npm install

### ISSUE THREAD

**Issue by NucsuM** [hcrudolph/osm4kids-backend#14]
'npm install' throw this error:

"Der Befehl "." ist entweder falsch geschrieben oder konnte nicht gefunden werden."
Maybe the "." in line 67 (./node_modules/.bin/tsc) can not resolved. `typings install` works. I use Windows 10.

Thanks

```
66 verbose lifecycle osm4kids@0.0.4~postinstall: CWD: C:\Users\ns\dev\osm4kids\osm4kids-backend
67 silly lifecycle osm4kids@0.0.4~postinstall: Args: [ '/d /s /c', 'typings install && ./node_modules/.bin/tsc' ]
68 silly lifecycle osm4kids@0.0.4~postinstall: Returned: code: 1  signal: null
69 info lifecycle osm4kids@0.0.4~postinstall: Failed to exec postinstall script
70 verbose stack Error: osm4kids@0.0.4 postinstall: `typings install && ./node_modules/.bin/tsc`
70 verbose stack Exit status 1
70 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:245:16)
70 verbose stack     at emitTwo (events.js:106:13)
70 verbose stack     at EventEmitter.emit (events.js:191:7)
70 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
70 verbose stack     at emitTwo (events.js:106:13)
70 verbose stack     at ChildProcess.emit (events.js:191:7)
70 verbose stack     at maybeClose (internal/child_process.js:850:16)
70 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
71 verbose pkgid osm4kids@0.0.4
72 verbose cwd C:\Users\ns\dev\osm4kids\osm4kids-backend
73 error Windows_NT 10.0.10240
74 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
75 error node v6.2.0
76 error npm  v3.8.9
77 error code ELIFECYCLE
78 error osm4kids@0.0.4 postinstall: `typings install && ./node_modules/.bin/tsc`
78 error Exit status 1
79 error Failed at the osm4kids@0.0.4 postinstall script 'typings install && ./node_modules/.bin/tsc'.
79 error Make sure you have the latest version of node.js and npm installed.
79 error If you do, this is most likely a problem with the osm4kids package,
79 error not with npm itself.
79 error Tell the author that this fails on your system:
79 error     typings install && ./node_modules/.bin/tsc
79 error You can get information on how to open an issue for this project with:
79 error     npm bugs osm4kids
79 error Or if that isn't available, you can get their info via:
79 error     npm owner ls osm4kids
79 error There is likely additional logging output above.
80 verbose exit [ 1, true ]

```

Full Log file -> [npm-debug.txt](https://github.com/hcrudolph/osm4kids-backend/files/333824/npm-debug.txt)

**Comment by hcrudolph** [comment]
That's a problem with the Linux path seperator `/`. So I guess all of [these](https://github.com/hcrudolph/osm4kids-backend/blob/master/package.json#L41-L44) won't work on Windows. I'll try to come up with some new scripts later today.
